version: '2.4'

services:

  ${project.artifactId}-vng:
    image: ${project.artifactId}:dev
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      - DJANGO_SETTINGS_MODULE=openzaak.conf.docker
      - SECRET_KEY=zpuC5WBe5qYTXyKg
      - IS_HTTPS=no
      - ALLOWED_HOSTS=*
      - CACHE_DEFAULT=${project.artifactId}-redis:6379/0
      - CACHE_AXES=${project.artifactId}-redis:6379/0
      - DB_HOST=${project.artifactId}-db
      - IMPORT_JSON=[{"model":"vng_api_common.jwtsecret","pk":2,"fields":{"identifier":"openzaak-alfresco-dev","secret":"424787bc-4b5f-4466-a57d-cd248020b363"}},{"model":"vng_api_common.jwtsecret","pk":3,"fields":{"identifier":"nrc-alfresco-dev","secret":"p9yxmqp6ZFYxA8jf"}},{"model":"vng_api_common.apicredential","pk":2,"fields":{"api_root":"http://tezza-acs.local:8080/alfresco/service/drc/v1/","label":"DRC","client_id":"b91d00dc-c762-4211-9c10-5918c81e5de6","secret":"8fBLx4sY4ZUWVjsjfYHtYwYS","user_id":"admin","user_representation":"admin"}},{"model":"vng_api_common.apicredential","pk":3,"fields":{"api_root":"http://notificaties-vng.local:8000/api/v1/","label":"NRC","client_id":"nrc-alfresco-dev","secret":"p9yxmqp6ZFYxA8jf","user_id":"admin","user_representation":"admin"}},{"model":"authorizations.authorizationsconfig","pk":1,"fields":{"api_root":"https://autorisaties-api.vng.cloud/api/v1/","component":"zrc"}},{"model":"authorizations.applicatie","pk":2,"fields":{"uuid":"f45c7d60-d377-4c5d-8a51-23973b0e3007","client_ids":"[\"openzaak-alfresco-dev\", \"nrc-alfresco-dev\"]","label":"openzaak-alfresco-dev","heeft_alle_autorisaties":true}},{"model":"notifications.notificationsconfig","pk":1,"fields":{"api_root":"http://notificaties-vng.local:8000/api/v1/"}},{"model":"accounts.user","fields":{"password":"pbkdf2_sha256$150000$zVSrCdZDeBZz$ofraCi01JF8NPF7bBAiKQWfCL/mFKO+fvjQsTRy2fsg=","last_login":"2020-01-20T13:41:29.645Z","is_superuser":true,"username":"admin","first_name":"","last_name":"","email":"admin@admin.org","is_staff":true,"is_active":true,"date_joined":"2019-12-20T21:54:05.373Z","groups":[],"user_permissions":[]}}]
      #- SUBPATH=/openzaak
    ports:
      - 8000:8000
    depends_on:
      - ${project.artifactId}-db
      - ${project.artifactId}-redis
    networks:
      dev_network:
        aliases:
          - ${project.artifactId}-vng.local 
 
  ${project.artifactId}-db:
    image: mdillon/postgis
    volumes:
      - vol_${project.artifactId}_postgres:/var/lib/postgresql/data    
    networks:
      dev_network:
        aliases:
          - ${project.artifactId}-db
  
  ${project.artifactId}-redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - vol_${project.artifactId}_redis:/data      
    networks:
      dev_network:
        aliases:
          - ${project.artifactId}-redis              
      
networks:
  dev_network:
    external: true  
    
volumes:
  vol_${project.artifactId}_postgres:
  vol_${project.artifactId}_redis:
